config/routes.rb
Rails.application.routes.draw do
  get 'chats/show'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "homes#top"

  get "home/about" => "homes#about"
  resources :books, only: [:index, :show, :edit, :create, :destroy, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  get "search" => "searches#search"

get 'chat/:id', to: 'chats#show', as: 'chat'
resources :chats, only: [:create]

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships,only: [:create,:destroy]
    get "followers" => "relationships#followers",as: "followers"
    get "followings" => "relationships#followings",as: "followings"
  end

  resources :groups do
    get "join" => "groups#join"
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  
  validates :rate, presence: true
  validates :rate, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1,
  }
  has_many :favorites, dependent: :destroy
  has_many :liked_users, through: :favorites, source: :user 
  has_many :book_comments, dependent: :destroy
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.search(search,word)
      if search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
      elsif search == "backword"
      @book == Book.where("title LIKE?","%#{word}")
      elsif search == "perfect_,match"
      @book = Book.where("#{word}")
      elsif search == "partial_match"
      @book = Book.where("%#{word}%")
      else
      @book = Book.all
      end
  end
  
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/chat.rb
class Chat < ApplicationRecord
      belongs_to :user
      belongs_to :room
      validates :message,length: {maximum: 140}
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users

  validates :name, presence: true
  validates :introduction, presence: true
  attachment :image, destroy: false
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower,class_name: "User"
  belongs_to :followed,class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :chats,dependent: :destroy
  has_many :users_room,dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable


  def follow(user_id)
      relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
      relationships.find_by(followed_id: user_id).destroy
  end

  def followings?(user)
      followings.include?(user)
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_rooms,dependent: :destroy
  has_many :chats,dependent: :destroy

  has_many :reverse_of_relationships,class_name: "Relationship",foreign_key: "followed_id",dependent: :destroy
  has_many :followers,through: :reverse_of_relationships,source: :follower
  has_many :relationships,class_name: "Relationship",foreign_key: "follower_id",dependent: :destroy
  has_many :followings,through: :relationships,source: :followed

  has_many :books

  has_many :group_users
  has_many :groups, through: :group_users

  has_many :favorites, dependent: :destroy
  has_many :liked_posts, through: :favorites, source: :book
  
  has_many :book_comments, dependent: :destroy
  attachment :profile_image, destroy: false

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }


def self.search(search,word)
    if search == "forward_match"
     @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
     @user == User.where("name LIKE?","%#{word}")
    elsif search == "perfect_match"
    @user = User.where("#{word}")
    elsif search == "partial_match"
     @user == User.where("%#{word}%")
    else
     @user = User.all
    end
end
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def show
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
  end

  def index
     @categorys = Category.where(is_valid: true)
    @q = Book.all.ransack(params[:q])
    @books = @q.result(distinct: true)
     @book = Book.new
  end

  def create
       @book = current_user.books.build(book_params)
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
  end

  def update
    if @book.update(book_params)
       redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book.destroy
    redirect_to books_path
  end
  
  def search
    @categorys = Category.where(is_valid: true)
    @category = Category.find(params[:id])
    @q = @category.books.all.ransack(params[:q])
    @notes = @q.result(distinct: true).page(params[:page])
    @title = @category.name
    render :index
  end
  private

  def book_params
    params.require(:book).permit(:title, :body,:rate,:category_id)
  end

  def ensure_correct_user
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
    end
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController

   def show
       @user = User.find_by(params[:id])
       rooms = current_user.user_rooms.pluck(:room_id)
       user_room = UserRoom.find_by(user_id: @user.id,room_id: rooms)

       room = nil

      if user_room.nil?
         room = Room.new
         room.save
         UserRoom.create(user_id: @user.id,room_id: room.id)
         UserRoom.create(user_id: current_user.id,room_id: room.id)
      else
         room = user_room.room
      end
         @chats = room.chats
         @chat = Chat.new(room_id: room.id)
   end

   def create
       @chat = current_user.chats.new(chat_params)
       @chat.save
   end


  private

  def chat_params
      params.require(:chat).permit(:message,:room_id)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
  end

  def update
    if @user.update(user_params)
       redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end
 
  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
   <div class="form-group row" id="star">
    <%= f.hidden_field :rate, class:'form-control book_rate'%>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>


 <script type="text/javascript">

    $('#star').raty({
      size     : 36,
      starOff:  '<%= asset_path('star-off.png') %>',
      starOn : '<%= asset_path('star-on.png') %>',
      starHalf: '<%= asset_path('star-half.png') %>',
      scoreName: 'note[rate]',
      half: true,
    });
  </script>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th>Rate</th>
      <th colspan="2"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr id="book_<%= book.id %>">
        <td><%= link_to user_path(book.user) do %>
          <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        　　　　　<td>
         <div id="star-rate-<%= book.id %>"></div>
          <script>
          $('#star-rate-<%= book.id %>').raty({
            size: 36,
            starOff:  '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
            half: true,
            readOnly: true,
            score: <%= book.rate %>,
          });
          </script>
        </td>

        <td class="favorite-btn"><%= render "favorites/favorite-btn", book: book %></td>
        <td class="comments-count">コメント数: <%= book.book_comments.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
    	<%= render 'layouts/errors', obj: @book %>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', book_path(@book), class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <%= render 'layouts/errors', obj: @book %>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'index', books: @books%>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @book.user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: Book.new %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr id="book_<%= @book.id %>">
  		    <td><%= link_to user_path(@book.user) do %>
            <%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-icon.jpg") %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, book_path(@book) %></td>
          <td><%= @book.body %></td>
          <td class="favorite-btn"><%= render "favorites/favorite-btn", book: @book %></td>
          <td class="comments-count">コメント数: <%= @book.book_comments.count %></td>
          <% if @book.user == current_user %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
            <td><%= link_to 'Destroy', book_path(@book), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%></td>
          <% end %>
        </tr>
      </table>
      <table class="book_comments">
        <%= render 'book_comments/index', book: @book %>
      </table>
      <%= form_with model:[@book,@book_comment] do |f| %>
        <%= f.text_area :comment, size:"90x5" %>
        <%= f.submit '送信'%>
      <% end %>
    </div>
  </div>
</div>

app/views/chats/create.js.erb
$(".message").append("<p style='text-align: left;'><%= @chat.message %></p>");

$("input[type=text]").val("")

app/views/chats/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-6">
            <h2>CHAT WITH <%= @user.name %></h2>
            
            <table class="message table">
              <thead>
                <tr>
                  <th style="text-align: left; font-size: 20px;"><%= current_user.name %></th>
                  <th style="text-align: right; font-size: 20px;"><%= @user.name %></th>
                </tr>
              </thead>
              <% @chats.each do |chat| %>
                <% if chat.user_id == current_user.id %>
                <tbody>
                  <tr>
                    <th>
                      <p style="text-align: left;"><%= chat.message %></p>
                    </th>
                    <th></th>
                  </tr>
                <% else %>
                  <tr>
                    <th></th>
                    <th>
                      <p style="text-align: right;"><%= chat.message %></p>
                    </th>
                  </tr>
                </tbody>
                <% end %>
              <% end %>
            </table>

              <%= form_with model: @chat, remote: true do |f| %>
              <%= f.text_field :message %>
              <%= f.hidden_field :room_id %>
              <%= f.submit "SEND", class:"btn btn-sm btn-success chat-btn" %>
              <% end %>
        </div>
    </div>
</div>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>

  <tr><th>フォロー数</th><th><%= link_to user.followings.count,user_followings_path(user.id) %></th></tr>
  <tr><th>フォロワー数</th><th><%= link_to user.followers.count,user_followers_path(user.id) %></th></tr>

<tr>
      <% if current_user.followings?(user) %>
      <th><%= link_to "Unfollow", user_relationships_path(user.id), method: :delete %></th>
      <% else %>
      <th><%= link_to "follow",user_relationships_path(user.id),method: :post,class: "btn btn-success" %></th>
      <% end %>
      
       <% if current_user != user && current_user.followings?(user) && user.followings?(current_user) %>
       <%= link_to 'chatを始める', chat_path(user.id), class: "ml-3" %>
       <% end %>


</tr>

</table>

<div class='row'>
  <%= link_to '',edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <%= link_to "グループを作成する", new_group_path %> | 
      <%= link_to "グループ一覧", groups_path %>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>

      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>